import Footer from './components/Footer';
import Header from './components/Header';
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
  description: 'next, react',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Header />
        <main className='main'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
